### ISSUE TITLE
I would love to have a list of all the Web Server back-end solutions that are actually stateful.

### ISSUE THREAD

**Issue by tacone** [davidgatti/Statefulness-aspect-of-NodeJS#2]
> I would love to have a list of all the Web Server back-end solutions that are actually stateful.

Pretty much all of them, but PHP and CGI. Surprised?

Actually statefulness is a big pain in the ass more often than not.

**Comment by davidgatti** [comment]
@tacone I'm not surprised, I know that other languages are, but I don't have experience with them to be writing in a meaningful manner about them. That is why I asked in the article for other to help up :)

My point is that this is not a well known feature nor, people use it, and I would love to know why do you think this feature is a **big pain**?

Ciao 🇮🇹

**Comment by tacone** [comment]
An interesting way to look at the problem may be to ask oneself why hosting providers used to offer PHP instead of Python and so on. Because far less problems for them.

The biggest problem is that when you have a long running process you get memory leaks. The memory footprint get larger, the disk swaps, the server crashes, and you need nodemon/forever to keep it up. Then you need days or weeks to hunt down the cause of memory leak. It's not pretty and it won't get any prettier.
Take PHP stateless approach as an opposite example: leak whatever you want, and after 3 months it will run as fast as the first day. Why? Because on every request the script is started from scratch and terminated right after.

The second problem you get is data-leaks: you don't want user data to be mistakenly exposed to other users. The more stuff is shared between requests, the more likely the mistake. You get the same problem with databases and caches of course, it's just one more point of failure.

Third: scaling. You can't scale your app without externalizing state in some way. The more you use stateful features, the more you have to redesign. Normally you should offload sessions and database to a set of external machines. If you use the state you have to do the same with it, and deal with concurrency.

The summary is that folks try to avoid shared state as much as they can to mitigate this kind of problems. For example, if you scope your variables to be available only in a given request and avoid singletons, you are much less likely to run into problem number 1.

There's nothing inherently wrong in shared state, it's just much harder than it seems at first sight.

Cheers

**Comment by davidgatti** [comment]
@tacone thank you for the explanation, and I must say it is bit strange to me. You are saying that you don't want to use the statefulness aspect of a language only because it might cause problems. I believe that the quality of the code and the skill of developer dictates that.

Based on your point of view and those of others we could give the following example:

_I won't learn to drive a car, because people say it is dangerous, and the more you drive the bigger the change to get in to an accident._ 

With such approach you'll miss some good times, and convenience a veinal can bring. The same goes with a feature of a language. 

When it comes to scalability, yes; but not every web app needs to be scaled. Not to mention that time example here doesn't apply. If you get 1 request a week, a lot of time will be 10 years. If you get 1 request a ms, then in few seconds you'll have an issue popping up.

Statefulness is nothing scary, or hard, it just require being organized. And the benefit in return are huge in my opinion.

**Comment by tacone** [comment]
I guess the best thing here, is to advise you to pursue your vision and see what it brings. Have fun!
